#!/bin/sh
# cd /Applications/Mathematica.app/Contents/MacOS
# mv Mathematica MathematicaApp
# cp [this file] /Applications/Mathematica.app/Contents/MacOS
# chmod +x Mathematica

resetcolor () {
  sleep 1
  defaults delete -g AppleHighlightColor
}

defaults write -g AppleHighlightColor -string "0.600000 0.500000 0.900000"
resetcolor & exec "$(dirname $0)/MathematicaApp"
